version: "3"
services:

  eureka-server:
    restart: always
    image: ebndnrk/browser-eureka-server
    ports:
      - '8761:8761'
    networks:
      - browser

  config-server:
    restart: always
    image: ebndnrk/browser-config-server
    ports:
      - '8888:8888'
    networks:
      - browser

  api-gateway:
    image: ebndnrk/browser-api-gateway
    ports:
      - '8765:8765'
    networks:
      - browser

  redis:
    image: redis:latest
    container_name: redis
    hostname: redis
    ports:
      - "6379:6379"
    networks:
      - browser

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: no
    networks:
      - browser

  browser-app:
    image: ebndnrk/browser-browser-app
    networks:
      - browser
    environment:
      AWS_SECRET_KEY: ${AWS_SECRET_KEY}
    deploy:
      replicas: 3



networks:
  browser:
    driver: bridge



