spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: index_service
            uri: lb://browser-app
            predicates:
              - Host=http://browser-app
              - Path=/**

server:
  port: 8765

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka







