apiVersion: apps/v1
kind: Deployment
metadata:
  name: browser-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: browser-app
  template:
    metadata:
      labels:
        app: browser-app
    spec:
      containers:
        - name: browser-app
          image: ebndnrk/browser-browser-app
          ports:
            - containerPort: 8080
          env:
            - name: AWS_SECRET_KEY
              value: AWS_SECRET_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: browser-app
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "internal"
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: browser-app